#####################################################################
## IGNORES

- ignore: { name: Replace case with fromMaybe }
- ignore: { name: Reduce duplication }
- arguments: [-XMultiWayIf, -XNoImplicitPrelude]