#####################################################################
## IGNORES

- ignore: { name: Use fromMaybe }
- ignore: { name: Reduce duplication }
- arguments: [-XMultiWayIf, -XNoImplicitPrelude]