language: haskell
dist: xenial

cache:
  directories:
    - $HOME/.cabal/packages
    - $HOME/.cabal/store
    - $HOME/.stack
    - $TRAVIS_BUILD_DIR/.stack-work

cabal: "2.4"

matrix:
  include:
    - env: BUILD=cabal
      ghc: "8.6.3"
    - env: BUILD=cabal
      ghc: "8.4.4"
    - env: BUILD=cabal
      ghc: "8.2.2"
      # --system-ghc is used to take advantage of language: haskell and save build time. If the stack resolver ghc and system-ghc become different, stack will download the right ghc
    - env: BUILD=stack ARGS="--resolver lts-11.22 --system-ghc"
      ghc: "8.2.2"
    - env: BUILD=stack ARGS="--resolver lts-12.26 --system-ghc"
      ghc: "8.4.4"
    - env: BUILD=stack ARGS="--resolver lts-13.1 --system-ghc"
      ghc: "8.6.3"
    - env: BUILD=stack ARGS="--resolver nightly --system-ghc"
      ghc: "8.6.3"

  allow_failures:
    - env: BUILD=stack ARGS="--resolver nightly --system-ghc"

before_install:
  - cabal new-install tasty-discover

install:
- |
  set -ex
  case "$BUILD" in
    cabal)
      cabal --numeric-version
      ghc --version
      ;;
    stack|werror)
      ghc --version
      PATH=$HOME/.local/bin:$PATH
      mkdir -p ~/.local/bin
      if [ `uname` = "Darwin" ]
      then
        travis_retry curl --insecure -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
      else
        travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      fi
      stack --numeric-version
      ;;
  esac
  set +ex

script:
- |
  set -ex
  case "$BUILD" in
    cabal)
      cabal new-update
      cabal new-build all
      ;;
    stack)
      stack --no-terminal $ARGS test --haddock --no-haddock-deps
      ;;
    werror)
      stack --no-terminal $ARGS test --haddock --no-haddock-deps --ghc-options -Werror --ghc-options -Wcompat --ghc-options -Wincomplete-record-updates --ghc-options -Wincomplete-uni-patterns --ghc-options -Wredundant-constraints
      ;;
  esac
  set +ex