name: tapl
version: 0.1.0
author: Shinya Yamaguchi
github: waddlaw/TAPL

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wnoncanonical-monad-instances
- -Wredundant-constraints
- -Wtabs

dependencies:
- base >= 4.11.0.0 && < 4.13.0.0
- haskeline >= 0.7.4.3 && < 0.7.6.0
- prettyprinter ^>= 1.2.1
- rio >= 0.1.7.0 && < 0.1.9.0
- transformers ^>= 0.5.5.0
- bool
- arith
- lambda-core
- lambda-untyped
- lambda-simple
- lambda-fullsimple

default-extensions:
- MultiWayIf
- NoImplicitPrelude

library:
  source-dirs: src

executables:
  proofb:
    main: app/ProofB.hs
    dependencies:
      - tapl
  nb:
    main: app/NB.hs
    dependencies:
      - tapl
  untyped-lambda:
    main: app/UntypedLambda.hs
    dependencies:
      - tapl
  simple-lambda:
    main: app/SimpleLambda.hs
    dependencies:
      - tapl
  fullsimple-lambda:
    main: app/FullSimpleLambda.hs
    dependencies:
      - tapl
  mkdoc:
    main: app/MkDoc.hs
    dependencies:
      - lucid ^>= 2.9.11
      - mmark ^>= 0.0.6.0
      - mmark-ext ^>= 0.2.1.1
      - megaparsec ^>= 7.0.4

benchmarks:
  gauge:
    main: bench/Gauge.hs
    dependencies:
      - tapl
      - gauge
  criterion:
    main: bench/Criterion.hs
    dependencies:
      - tapl
      - criterion
