name: tapl
version: 0.1.0
author: Shinya Yamaguchi
github: waddlaw/TAPL

extra-source-files:
- package.yaml

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wnoncanonical-monad-instances
- -Wredundant-constraints
- -Wtabs

dependencies:
- rio
- base
- haskeline
- prettyprinter
- transformers
- bool
- arith
- lambda-core
- lambda-untyped
- lambda-simple
- lambda-fullsimple

library:
  source-dirs: src

executables:
  proofb:
    main: app/ProofB.hs
    dependencies:
      - tapl
    ghc-options:
      - -threaded
      - -rtsopts
  nb:
    main: app/NB.hs
    dependencies:
      - tapl
    ghc-options:
      - -threaded
      - -rtsopts
  untyped-lambda:
    main: app/UntypedLambda.hs
    dependencies:
      - tapl
    ghc-options:
      - -threaded
      - -rtsopts
  simple-lambda:
    main: app/SimpleLambda.hs
    dependencies:
      - tapl
    ghc-options:
      - -threaded
      - -rtsopts
  fullsimple-lambda:
    main: app/FullSimpleLambda.hs
    dependencies:
      - tapl
    ghc-options:
      - -threaded
      - -rtsopts
  # mkdoc:
  #   main: app/MkDoc.hs
  #   dependencies:
  #     - lucid
  #     - mmark
  #     - mmark-ext
  #   ghc-options:
  #     - -threaded
  #     - -rtsopts

benchmarks:
  gauge:
    main: bench/Gauge.hs
    dependencies:
      - tapl
      - gauge
  criterion:
    main: bench/Criterion.hs
    dependencies:
      - tapl
      - criterion
