name: tapl
version: 0.0.0
author: Shinya Yamaguchi
github: waddlaw/TAPL

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wnoncanonical-monad-instances
  - -Wredundant-constraints
  - -Wtabs

dependencies:
  - base
  - containers
  - hashable
  - parsers
  - prettyprinter
  - QuickCheck
  - text
  - transformers
  - trifecta
  - unordered-containers

library:
  source-dirs: src

executables:
  proofb:
    main: app/ProofB.hs
    dependencies:
      - tapl
      - haskeline
    ghc-options:
      - -threaded
      - -rtsopts
  nb:
    main: app/NB.hs
    dependencies:
      - tapl
      - haskeline
    ghc-options:
      - -threaded
      - -rtsopts
  untyped-lambda:
    main: app/UntypedLambda.hs
    dependencies:
      - tapl
      - haskeline
    ghc-options:
      - -threaded
      - -rtsopts
  mkdoc:
    main: app/MkDoc.hs
    dependencies:
      - lucid
      - mmark
      - mmark-ext
    ghc-options:
      - -threaded
      - -rtsopts

tests:
  test:
    main: Driver.hs
    source-dirs: test
    dependencies:
      - tapl
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-quickcheck

benchmarks:
  gauge:
    main: bench/Gauge.hs
    dependencies:
      - tapl
      - gauge
  criterion:
    main: bench/Criterion.hs
    dependencies:
      - tapl
      - criterion
