resolver: lts-12.19
packages:
- .
- ./subs/lambda-core
- ./subs/lambda-simple
- ./subs/lambda-untyped
- ./subs/lambda-fullsimple

# extra-deps:
#   - git: https://github.com/mmark-md/mmark
#     commit: 4febdb513633d6f18a5df2fd175ece937a775a72

build:
  haddock: false
  haddock-arguments:
    haddock-args:
      - --odir=docs
