resolver: lts-12.9
# extra-deps:
#   - git: https://github.com/mmark-md/mmark
#     commit: 4febdb513633d6f18a5df2fd175ece937a775a72

build:
  haddock: false
  haddock-arguments:
    haddock-args:
      - --odir=docs
