resolver: lts-14.16
packages:
  - .
  - ./subs/term
  - ./subs/bool
  - ./subs/arith
  - ./subs/lambda-core
  - ./subs/lambda-simple
  - ./subs/lambda-untyped
  - ./subs/lambda-fullsimple
  - ./subs/featherweight-java
  - ./subs/recon

extra-deps:
- prettyprinter-1.3.0

build:
  haddock: false
  haddock-arguments:
    haddock-args:
      - --odir=docs
