resolver: lts-13.1
packages:
- .
- ./subs/term
- ./subs/bool
- ./subs/arith
- ./subs/lambda-core
- ./subs/lambda-simple
- ./subs/lambda-untyped
- ./subs/lambda-fullsimple

build:
  haddock: false
  haddock-arguments:
    haddock-args:
      - --odir=docs
