resolver: lts-14.3
packages:
  - .
  - ./subs/term
  - ./subs/bool
  - ./subs/arith
  - ./subs/lambda-core
  - ./subs/lambda-simple
  - ./subs/lambda-untyped
  - ./subs/lambda-fullsimple
  - ./subs/featherweight-java

extra-deps:
  - prettyprinter-1.3.0
  - rio-0.1.12.0

build:
  haddock: false
  haddock-arguments:
    haddock-args:
      - --odir=docs
