name:                lambda-core
version:             0.1.0.0
github:              "waddlaw/TAPL"
author:              "Shinya Yamaguchi"
maintainer:          "ingronze@gmail.com"
copyright:           "2018-2019 Shinya Yamaguchi"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/waddlaw/TAPL#readme>

dependencies:
- base >= 4.7 && < 5
- base-noprelude
- prettyprinter
- rio
- trifecta

library:
  source-dirs: src
  other-modules:
  - Prelude

tests:
  lambda-core-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - lambda-core
