name: arith
version: 0.1.0.0
github: 'waddlaw/TAPL'
author: 'Shinya Yamaguchi'
maintainer: 'ingronze@gmail.com'
copyright: '2018-2019 Shinya Yamaguchi'

dependencies:
  - base >= 4.7 && < 5
  - lambda-core
  - prettyprinter
  - rio
  - trifecta

default-extensions:
  - MultiWayIf
  - NoImplicitPrelude
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wnoncanonical-monad-instances
  - -Wredundant-constraints
  - -Wtabs

library:
  source-dirs: src

tests:
  arith-test:
    main: Driver.hs
    source-dirs: test
    dependencies:
      - arith
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-quickcheck
