name:                lambda-untyped
version:             0.1.0.0
github:              "waddlaw/tapl"
license:             BSD3
author:              "Shinya Yamaguchi"
maintainer:          "example@example.com"
copyright:           "2018-2019 Shinya Yamaguchi"

extra-source-files:
- README.md
- ChangeLog.md

description: untyped lambda

dependencies:
- base >= 4.7 && < 5
- base-noprelude
- lambda-core
- parsers
- prettyprinter
- rio
- trifecta

library:
  source-dirs: src
  other-modules:
  - Prelude

tests:
  lambda-untyped-test:
    main: Driver.hs
    source-dirs: test
    dependencies:
    - lambda-untyped
    - tasty
    - tasty-discover
    - tasty-hunit
    - tasty-quickcheck
