name:                lambda-untyped
version:             0.1.0.0
github:              "githubuser/lambda-untyped"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/lambda-untyped#readme>

dependencies:
- base >= 4.7 && < 5
- lambda-core
- parsers
- prettyprinter
- rio
- trifecta

library:
  source-dirs: src

tests:
  lambda-untyped-test:
    main: Driver.hs
    source-dirs: test
    dependencies:
    - lambda-untyped
    - tasty
    - tasty-discover
    - tasty-hunit
    - tasty-quickcheck
