name:                term
version:             0.1.0.0
github:              "waddlaw/TAPL"
author:              "Shinya Yamaguchi"
maintainer:          "ingronze@gmail.com"
copyright:           "2018-2019 Shinya Yamaguchi"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/waddlaw/TAPL#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- rio

library:
  source-dirs: src

tests:
  term-test:
    main: Driver.hs
    source-dirs: test
    dependencies:
    - term
    - tasty
    - tasty-discover
    - tasty-hunit
    - tasty-quickcheck
