name: cabal

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "00 15 * * *"

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        ghc: ["8.6.5", "8.8.2"]
        cabal: ["3.0"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache ~/.cabal/store
      uses: actions/cache@v1.1.2
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-v1-cabal-store

    - name: Cache dist-newstyle
      uses: actions/cache@v1.1.2
      with:
        path: dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-v1-cabal-dist
        
    - name: Install dependencies
      run: |
        cabal v2-update
        cabal v2-configure --disable-optimization --write-ghc-environment-files=always -j2
        cabal v2-build --only-dependencies
        
    - name: Build
      run: |
        cabal v2-build
        cabal v2-install all:exes --overwrite-policy=always