name: cabal

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "00 15 * * *"

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        ghc: ["8.10"]
        cabal: ["3.2"]
        cache-version: ["2020-11-28"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache cabal
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cache-version }}-cabal

    - name: Install dependencies
      run: |
        cabal update
        cabal configure --disable-optimization --write-ghc-environment-files=always -j2
        cabal build all --only-dependencies
        
    - name: Build
      run: |
        cabal build
        cabal install all:exes --overwrite-policy=always