name: format

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "00 15 * * *"

jobs:
  format:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        cache-version: ["2020-04-25"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: "8.8.3"
        cabal-version: "3.0"

    - uses: actions/cache@v1
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.cache-version }}-cabal

    - name: Install cabal-fmt, ormolu
      run: |
        cabal update
        cabal install cabal-fmt ormolu --overwrite-policy=always --install-method=copy -j2

    - name: Apply cabal-fmt
      run: |
        export PATH=~/.cabal/bin/:$PATH
        cabal-fmt -i *.cabal
        cabal-fmt -i subs/*/*.cabal
        git --no-pager diff --exit-code

    - name: Apply ormolu
      run: |
        export PATH=~/.cabal/bin/:$PATH
        ormolu --mode inplace $(find app bench src subs -type f -name "*.hs")
        git --no-pager diff --exit-code