name: stack

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "00 15 * * *"

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        cache-version: ["2020-11-28"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: "8.10"
        stack-version: "2.5.1"
        enable-stack: true

    # See: https://github.com/actions/cache/issues/445
    - name: Install GNU tar
      if: runner.os == 'macOS'
      run: |
        brew install gnu-tar
        echo "/usr/local/opt/gnu-tar/libexec/gnubin" >> $GITHUB_PATH

    - name: Cache ~/.stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.resolver }}-${{ matrix.cache-version }}-stack

    - name: Install dependencies
      run: stack test --only-dependencies --system-ghc

    - name: Build
      run: |
        stack test    --fast --pedantic --system-ghc
        stack install --fast --pedantic --system-ghc