name: stack

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "00 15 * * *"

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        cache-version: ["2020-04-25"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: "8.8.3"
        cabal-version: "3.0"

    - name: Cache ~/.stack
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.cache-version }}-stack

    - name: Install dependencies
      run: stack test --only-dependencies --system-ghc

    - name: Build
      run: |
        stack test    --fast --pedantic --system-ghc
        stack install --fast --pedantic --system-ghc